import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game,RULES} from '../game.js';
function cmd(g,seat,action){return g.command(seat,{seq:g.players[seat].lastSeq+1,action});}
function advance(g,ms){for(let n=0;n<ms/RULES.tick;n++){g.step();g.finishIfNeeded();}}
function setup(){const g=new Game('TEST');for(let i=0;i<2;i++){g.addPlayer(`Player ${i+1}`);g.connection(i,true);cmd(g,i,'ready');}return g;}
function live(){const g=setup();advance(g,3000);return g;}
test('both ready and three second countdown gate damage and actions',()=>{const g=setup();assert.equal(g.phase,'countdown');assert.ok(cmd(g,0,'smite'));advance(g,3000);assert.equal(g.hp,10000);advance(g,1000);assert.equal(g.hp,9800);});
test('free Smite resolves after 200 ms once per round; empowerment removed',()=>{const g=live();cmd(g,0,'smite');advance(g,150);assert.equal(g.hp,10000);advance(g,50);assert.equal(g.hp,9400);assert.ok(cmd(g,0,'smite'));assert.ok(cmd(g,0,'empowered'));assert.equal(g.players[0].energy,3);});
for(const first of [0,1])test(`same-tick lethal Smites award only first accepted caster, seat ${first}`,()=>{const g=live();g.hp=600;cmd(g,first,'smite');cmd(g,1-first,'smite');advance(g,200);assert.equal(g.players[first].score,1);assert.equal(g.players[1-first].score,0);assert.equal(g.events.filter(e=>e.type==='kill').length,1);assert.equal(g.events.at(-1).type,'fizzle');});
test('early nonlethal Smite does not steal the later killing blow',()=>{const g=live();g.hp=700;cmd(g,1,'smite');cmd(g,0,'smite');advance(g,200);assert.deepEqual(g.players.map(p=>p.score),[1,0]);const impacts=g.events.filter(e=>e.type==='impact');assert.deepEqual(impacts.map(e=>[e.before,e.after]),[[700,100],[100,0]]);});
test('different deadlines precede acceptance order',()=>{const g=live();g.hp=600;cmd(g,0,'burst');cmd(g,1,'smite');advance(g,400);assert.deepEqual(g.players.map(p=>p.score),[0,1]);assert.equal(g.players[0].revealedEnergy,2);});
test('Smite precedes simultaneous environment and auto damage without shared points',()=>{const g=live();advance(g,800);g.hp=600;cmd(g,0,'attack');cmd(g,1,'smite');advance(g,200);assert.deepEqual(g.players.map(p=>p.score),[0,1]);});
test('environment alone awards no point and wins equal-time auto race',()=>{const g=live();advance(g,950);g.hp=200;cmd(g,0,'attack');cmd(g,1,'attack');advance(g,50);assert.deepEqual(g.players.map(p=>p.score),[0,0]);});
test('auto tie priority alternates by round and never shares points',()=>{for(const round of [1,2]){const g=live();g.round=round;g.hp=100;cmd(g,0,'attack');cmd(g,1,'attack');advance(g,500);assert.equal(g.players[(round-1)%2].score,1);assert.equal(g.players[round%2].score,0);}});
test('energy reserved immediately and cannot be overspent',()=>{const g=live();g.players[0].energy=g.players[0].revealedEnergy=1;cmd(g,0,'stun');assert.equal(g.players[0].energy,0);assert.equal(g.view(1).players[0].energy,1);assert.ok(cmd(g,0,'burst'));advance(g,300);assert.equal(g.view(1).players[0].energy,0);});
test('regeneration occurs only on next round, is capped, and ready cannot farm it',()=>{const g=live();cmd(g,0,'burst');advance(g,400);g.hp=100;advance(g,600);cmd(g,0,'ready');cmd(g,0,'ready');assert.equal(g.players[0].energy,2);cmd(g,1,'ready');assert.equal(g.players[0].energy,3);assert.equal(g.smiteDamage,700);g.players[0].energy=6;g.phase='results';cmd(g,0,'ready');cmd(g,1,'ready');assert.equal(g.players[0].energy,6);});
test('Burst and Smite can overlap for an 850 damage first-round combo',()=>{const g=live();cmd(g,0,'burst');advance(g,200);cmd(g,0,'smite');advance(g,200);assert.equal(g.hp,9150);assert.equal(g.players[0].energy,2);});
test('Disrupt windup, action lock and precise expiration',()=>{const g=live();cmd(g,0,'stun');advance(g,250);assert.equal(g.players[1].stunnedUntil,0);advance(g,50);assert.equal(g.players[1].stunnedUntil,3900);for(const a of ['attack','smite','burst','stun'])assert.match(cmd(g,1,a),/Stunned/);advance(g,550);assert.ok(cmd(g,1,'smite'));advance(g,50);assert.equal(cmd(g,1,'smite'),null);});
test('stun skips auto attacks without shifting their cadence',()=>{const g=live();cmd(g,1,'attack');cmd(g,0,'stun');advance(g,500);assert.equal(g.hp,10000);advance(g,400);assert.equal(g.hp,10000);advance(g,100);assert.equal(g.hp,9700);});
test('committed damage survives stun and simultaneous Disrupts can both land',()=>{const g=live();cmd(g,0,'stun');cmd(g,1,'stun');advance(g,150);cmd(g,1,'smite');advance(g,150);assert.ok(g.players.every(p=>p.stunnedUntil>g.time));advance(g,50);assert.equal(g.hp,9400);});
test('disconnect freezes stun and committed casts until reconnect',()=>{const g=live();cmd(g,0,'stun');advance(g,300);const t=g.time;g.connection(1,false,1000);advance(g,5000);assert.equal(g.time,t);assert.equal(g.players[1].stunnedUntil,3900);g.connection(1,true);advance(g,600);assert.equal(cmd(g,1,'smite'),null);});
test('duplicate, stale and malformed actions never mutate resources',()=>{const g=live();const msg={seq:2,action:'burst'};assert.equal(g.command(0,msg),null);assert.ok(g.command(0,msg));for(const action of ['constructor','toString','__proto__',{},null])assert.ok(cmd(g,0,action));assert.equal(g.players[0].energy,2);assert.equal(g.pending.length,1);});
test('attack toggles never accelerate cadence',()=>{const g=live();advance(g,450);cmd(g,0,'attack');cmd(g,0,'attack');cmd(g,0,'attack');assert.equal(g.hp,10000);advance(g,50);assert.equal(g.hp,9900);});
test('post-kill spells fizzle, reveal cost, cannot stun and block ready until settled',()=>{const g=live();g.hp=500;cmd(g,0,'smite');cmd(g,1,'stun');advance(g,200);assert.equal(g.phase,'results');assert.ok(cmd(g,0,'ready'));advance(g,100);assert.equal(g.players[0].stunnedUntil,0);assert.equal(g.players[1].revealedEnergy,2);assert.equal(g.events.at(-1).type,'fizzle');});
test('forfeit validates 30-second grace and rematch clears status',()=>{const g=live();g.connection(1,false,1000);assert.ok(g.command(0,{seq:2,action:'forfeit'},30999));assert.equal(g.command(0,{seq:3,action:'forfeit'},31000),null);assert.equal(g.phase,'final');g.connection(1,true);cmd(g,0,'ready');cmd(g,1,'ready');assert.equal(g.round,1);assert.equal(g.players[0].energy,3);});
test('seven round evolution, monster rotation, final draw, full rematch reset',()=>{const g=live();const names=new Set();for(let r=1;r<=7;r++){assert.equal(g.smiteDamage,500+r*100);names.add(g.view(0).monster.name);while(g.phase==='live')advance(g,50);if(r<7){cmd(g,0,'ready');cmd(g,1,'ready');advance(g,3000);}}assert.equal(names.size,3);assert.equal(g.phase,'final');assert.match(g.result,/drawn/);cmd(g,0,'ready');cmd(g,1,'ready');assert.equal(g.smiteDamage,600);assert.deepEqual(g.players.map(p=>p.energy),[3,3]);assert.ok(g.players.every(p=>!p.stunUsed&&p.stunnedUntil===0));});
test('live history is bounded while recap retains decision history',()=>{const g=live();cmd(g,0,'attack');advance(g,5000);assert.ok(g.view(0).events.length<=12);g.phase='results';assert.ok(g.view(0).events.length>12);});
