import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game,RULES} from '../game.js';
function setup(){const g=new Game('TEST');for(let i=0;i<2;i++){g.addPlayer(`Player ${i+1}`);g.connection(i,true);g.command(i,{seq:1,action:'ready'});}return g;}
function advance(g,ms){for(let n=0;n<ms/RULES.tick;n++){g.step();g.finishIfNeeded();}}
function live(){const g=setup();advance(g,3000);return g;}
function cmd(g,seat,action){return g.command(seat,{seq:g.players[seat].lastSeq+1,action});}
test('both must ready; countdown deals no damage and blocks actions',()=>{const g=setup();assert.equal(g.phase,'countdown');assert.ok(cmd(g,0,'smite'));advance(g,3000);assert.equal(g.hp,10000);advance(g,1000);assert.equal(g.hp,9800);});
test('Smite deals 600 after exactly 200 ms and shares availability',()=>{const g=live();assert.equal(cmd(g,0,'smite'),null);advance(g,150);assert.equal(g.hp,10000);advance(g,50);assert.equal(g.hp,9400);assert.ok(cmd(g,0,'empowered'));assert.equal(g.players[0].energy,6);});
test('empowerment reserves energy, hides choice until impact, consumes both Smites',()=>{const g=live();cmd(g,0,'empowered');assert.equal(g.players[0].energy,4);const opponent=g.view(1);assert.equal(opponent.players[0].energy,6);assert.equal(opponent.pending[0].action,'smite');assert.equal(opponent.pending[0].cost,undefined);assert.equal(opponent.events.at(-1).action,'smite');assert.ok(cmd(g,0,'smite'));advance(g,200);assert.equal(g.hp,9150);assert.equal(g.view(1).players[0].energy,4);});
test('energy cannot be overspent even before previous casts resolve',()=>{const g=live();g.players[0].energy=g.players[0].revealedEnergy=2;cmd(g,0,'empowered');assert.ok(cmd(g,0,'burst'));assert.equal(g.players[0].energy,0);assert.equal(g.players[0].burstUsed,false);});
test('Burst and Smite overlap with deterministic 1100 damage combo',()=>{const g=live();cmd(g,0,'burst');advance(g,200);cmd(g,0,'empowered');advance(g,150);assert.equal(g.hp,10000);advance(g,50);assert.equal(g.hp,8900);assert.equal(g.players[0].energy,3);assert.equal(g.pending.length,0);});
test('duplicate and stale action sequences do not mutate damage or toggles',()=>{const g=live();const msg={seq:2,action:'attack'};assert.equal(g.command(0,msg),null);assert.ok(g.command(0,msg));assert.equal(g.players[0].attack,true);cmd(g,0,'burst');const energy=g.players[0].energy;assert.ok(g.command(0,{seq:3,action:'burst'}));assert.equal(g.players[0].energy,energy);});
test('attack toggling never accelerates or resets fixed attack cadence',()=>{const g=live();advance(g,450);cmd(g,0,'attack');cmd(g,0,'attack');cmd(g,0,'attack');assert.equal(g.hp,10000);advance(g,50);assert.equal(g.hp,9900);cmd(g,0,'attack');advance(g,450);cmd(g,0,'attack');advance(g,50);assert.equal(g.hp,9600);});
test('both players contributing to a lethal batch each receive a point',()=>{const g=live();g.hp=700;cmd(g,0,'smite');cmd(g,1,'smite');advance(g,200);assert.deepEqual(g.players.map(p=>p.score),[1,1]);assert.equal(g.hp,0);assert.equal(g.phase,'results');});
test('environment-only lethal batch earns no points',()=>{const g=live();g.hp=200;advance(g,1000);assert.deepEqual(g.players.map(p=>p.score),[0,0]);});
test('auto attack contribution alongside environment earns point',()=>{const g=live();advance(g,950);g.hp=250;cmd(g,0,'attack');advance(g,50);assert.deepEqual(g.players.map(p=>p.score),[1,0]);});
test('auto attack and rival Smite in lethal tick both earn points',()=>{const g=live();advance(g,300);g.hp=600;cmd(g,0,'smite');cmd(g,1,'attack');advance(g,200);assert.deepEqual(g.players.map(p=>p.score),[1,1]);});
test('late pending action resolves after death and reveals committed spending',()=>{const g=live();g.hp=500;cmd(g,0,'smite');cmd(g,1,'burst');advance(g,200);assert.equal(g.phase,'results');assert.equal(g.view(0).players[1].energy,6);assert.ok(cmd(g,0,'ready'));advance(g,200);assert.equal(g.view(0).players[1].energy,5);assert.equal(g.events.at(-1).type,'fizzle');assert.deepEqual(g.players.map(p=>p.score),[1,0]);});
test('disconnect pauses casts and HP; reconnect resumes preserved timing',()=>{const g=live();cmd(g,0,'smite');advance(g,100);g.connection(1,false,1000);advance(g,5000);assert.equal(g.hp,10000);assert.equal(g.time,3100);g.connection(1,true,2000);advance(g,100);assert.equal(g.hp,9400);});
test('forfeit requires a disconnected opponent and 30 second grace',()=>{const g=live();g.connection(1,false,1000);assert.ok(g.command(0,{seq:2,action:'forfeit'},30999));assert.equal(g.command(0,{seq:3,action:'forfeit'},31000),null);assert.equal(g.phase,'final');assert.equal(g.forfeitWinner,0);});
test('seven rounds preserve energy, draw scoring and rematch fully resets',()=>{const g=live();cmd(g,0,'empowered');advance(g,200);for(let round=1;round<=7;round++){while(g.phase==='live')advance(g,50);assert.equal(g.round,round);assert.equal(g.players[0].energy,4);if(round<7){cmd(g,0,'ready');cmd(g,1,'ready');advance(g,3000);}}assert.equal(g.phase,'final');assert.match(g.result,/drawn/);cmd(g,0,'ready');cmd(g,1,'ready');assert.equal(g.round,1);assert.equal(g.phase,'countdown');assert.deepEqual(g.players.map(p=>p.energy),[6,6]);assert.deepEqual(g.players.map(p=>p.score),[0,0]);});
